### PR TITLE
Add seeding script

### PR DESCRIPTION
**Pull request by bumi**
the seed script allows to execute certain contract function to easily
setup testing data for locally deployed contracts to a development
chain.

### CODE REVIEW

**Comment by bumi** [comment]
@skddc I need to run that async contract calls sequential. Can I do that somehow differnetly, without the `asyc` dependency?

**Comment by galfert** [comment]
@bumi do the contract calls return Promises?

**Comment by bumi** [comment]
no, they use callbacks, like:
```javascript
Kredits.contractMethod(argumens, function(err, response) {
  console.log(response);
});
```

I've tried to wrap that in a Promise but could not get it work to run sequentially.

**Comment by galfert** [comment]
I think it's possible with some recursive function calling, but it wouldn't look remotely as simple as with `async` :)

If you really want to get rid of the dependency, I would be happy to give it a try.

**Comment by bumi** [comment]
nah, I've spent enough time on that. :) thanks!
also thought it might work with async/await - but could not get that working either.

**Comment by bumi** [comment]
I am merging this then.

**Comment by galfert** [comment]
> also thought it might work with async/await - but could not get that working either.

I think that only works with Promises.

**Pull request merged**
